# Configurations
title: JDK新特性
author: PasseRR
description: Build Jekyll site with the GitBook style.

version: 1.0
gitbook_version: 3.2.3

baseurl: '/jdk-features'
# 主题cdn地址
theme-cdn: 'https://fastly.jsdelivr.net/gh/PasseRR/jekyll-gitbook-theme'
#theme-cdn: '/jdk-features'
cdn: 'https://fastly.jsdelivr.net/gh/PasseRR/jdk-features/docs'
#cdn: '/jdk-features'
# 目录定义
collections:
  chapters:
    permalink: /:categories/:name:output_ext
    output: true
rss: RSS

toc:
  enabled: false
  h_min: 1
  h_max: 3

# Search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [ 404.md, search.md ]

# markdown render engine.
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

markdown_ext: markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink: /:categories/:name:output_ext

exclude:
  - _drafts

destination: ./_site
incremental: false
regenerate: true

# google分析gtag
ga: G-1L1DPX3PFD
# 百度统计hm
hm: 95dc7dd4cb7bead6ab60cf81fab91330

remote_theme: PasseRR/jekyll-gitbook-theme

relative_links:
  enabled:     true
  collections: true

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-relative-links
