source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
gem "jekyll"
gem 'jekyll-feed'
gem 'jemoji'
gem 'webrick'
gem "jekyll-remote-theme"
gem "jekyll-sitemap"
gem "jekyll-relative-links"